apiVersion: v2
name: mcp-atlassian
description: A Helm chart for Kubernetes
icon: https://raw.githubusercontent.com/modelcontextprotocol/docs/main/logo/light.svg

# A chart can be either an "application" or a "library" chart.
#
# Application charts package versioned templates that can be deployed.
#
# Library charts provide utilities pulled in as dependencies.
# They cannot be deployed directly because no templates are defined.
type: application

# Bump this chart version whenever the chart or its templates change.
# Versions are expected to follow Semantic Versioning (https://semver.org/).
version: 0.2.28

# This is the application version. Bump it whenever the app itself changes.
# It does not need to follow Semantic Versioning. Quotes are recommended.
dependencies:
  - name: mcp-library
    version: 0.1.4
    repository: https://tekulvw.github.io/mcp-helm/
appVersion: "1.16.0"
